#!/usr/bin/env bash

set -e

VM_HOME=$HOME/vm

name=${1:-nixos}
vdi=${2:-/nix/store/ddjff980pc276iblz6hrx2zda3xpcj6d-zalora-virtualbox-nixops.vdi}
pubkey=${3:-$HOME/.ssh/id_rsa.pub}
sshport=${4:-2222}
vmdata=${5:-$VM_HOME/$name}

usage() {
	echo "$1" >&2
	echo "usage: $0 name vdi [pubkey] [sshport] [vmdata]" >&2
	echo "defaults: pubkey=$pubkey sshport=${sshport} vmdata=$vmdata" >&2
	echo >&2
	exit 1
}

{ # protect against ^C and starbucks wi-fi

[ $# -lt 2 -o $# -gt 5 ] && usage
[ ! -f $vdi ] && usage "vdi: $vdi: file not found"
[ ! -f $pubkey ] && usage "pubkey: $pubkey: file not found"

echo >&2
echo "mkvbox: name=$name vdi=$vdi pubkey=$pubkey sshport=${sshport} vmdata=$vmdata" >&2
echo >&2

set -x

mkdir -p "$vmdata"
VBoxManage createvm --name "$name" --ostype Linux26_64 --register
VBoxManage clonehd "$vdi" "$vmdata"/disk1.vdi
VBoxManage storagectl "$name" --name SATA --add sata --portcount 30 --hostiocache on --bootable on
VBoxManage storageattach "$name" --storagectl SATA --port 0 --device 0 --type hdd --medium "$vmdata"/disk1.vdi
VBoxManage createhd --filename "$vmdata"/db.vdi --size 61440
VBoxManage storageattach "$name" --storagectl SATA --port 1 --device 0 --type hdd --medium "$vmdata"/db.vdi
VBoxManage guestproperty set "$name" /VirtualBox/GuestInfo/Charon/ClientPublicKey "$(cat $pubkey)"
VBoxManage modifyvm "$name" --memory 4096
VBoxManage modifyvm "$name" --natpf1 "SSH,tcp,,${sshport},,22"
VBoxManage startvm "$name" --type headless

VBoxManage showvminfo "$name" | head >&2
set +x

echo >&2
echo add this to your ssh config: >&2
echo >&2

cat > /dev/stdout << EOF
Host ${name}
	User root
	HostName localhost
	Port ${sshport}
EOF

}
